#!/usr/bin/env bash
set -euo pipefail

cd ~/projects/uav_mec_sci
source .venv/bin/activate
export PYTHONPATH=$(pwd)
export TORCH_NUM_THREADS=1
export TORCH_INTEROP_THREADS=1

# 快速验证版：先只跑 seed=72，建议 NUM_EPISODES=200。
# 如果中途 avg_ratio_target_delta 明显下降、eval cost 不恶化，再跑正式 700 episodes。
DEVICE=auto \
SEED=72 \
NUM_EPISODES=200 \
EPISODE_LENGTH=20 \
EVAL_EVERY=5 \
OMEGA1=50 \
OMEGA2=1 \
DEADLINE_SCALE=2.5 \
TASK_LOCAL_CPU_MIN=2000 \
TASK_LOCAL_CPU_MAX=5000 \
STAGE1_PREFIX=proposed_full_stage1_main_d25_seed72_ep200_formal10 \
RUN_NAME=proposed_full_stage2_main_d25_seed72_ep200_v7_ratio_distill_verify \
CKPT_PREFIX=proposed_full_stage2_main_d25_seed72_ep200_v7_ratio_distill_verify \
MODEL_REFINE=1 \
MODEL_REFINE_MAX_TASKS=16 \
MODEL_REFINE_RATIO=1 \
MODEL_REFINE_SCHED=1 \
REFINED_RATIO_DISTILL=1 \
REFINED_RATIO_BC_COEF_START=0.50 \
REFINED_RATIO_BC_COEF_END=0.15 \
RATIO_BC_COEF_START=0.020 \
RATIO_BC_COEF_END=0.000 \
RATIO_REG_COEF_START=0.002 \
RATIO_REG_COEF_END=0.0005 \
RATIO_FLOOR_TARGET=0.05 \
RATIO_MEAN_TARGET=0.060 \
RATIO_STD_TARGET=0.015 \
ACTOR_POLICY_COEF_START=0.0003 \
ACTOR_POLICY_COEF_END=0.0012 \
ACTOR_MOVE_SCHED_BC_COEF_START=1.00 \
ACTOR_MOVE_SCHED_BC_COEF_END=0.30 \
NEIGHBOR_COLLAB_COEF_START=0.10 \
NEIGHBOR_COLLAB_COEF_END=0.30 \
NEIGHBOR_PROB_TARGET=0.15 \
LOCAL_DOMINANCE_COEF_START=0.05 \
LOCAL_DOMINANCE_COEF_END=0.15 \
SELF_IMITATION_COEF_START=0.30 \
SELF_IMITATION_COEF_END=0.80 \
python3 -m train.train_proposed_full_stage2_converge_v7_ratio_distill
